### ISSUE TITLE
Heathcheck panic

### ISSUE THREAD

**Issue by Chester-Ong** [opstree/druid-exporter#17]
druid-exporter requires druid-query server to constantly be running. Once you kill the service, druid-exporter automatically panics after a heathcheck query is passed.

```
{"err":"Get \"<QUERY ENDPOINT>:8888/status/health\": dial tcp 123.123.123.123:8888: connect: connection refused","level":"error","msg":"Error while making GET request for druid healthcheck","ts":"2020-05-26T01:47:08.674Z"}
{"level":"info","msg":"GET request is successful on druid healthcheck","ts":"2020-05-26T01:47:08.683Z","url":"<QUERY ENDPOINT>:8888/status/health"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x731e30]

goroutine 336113 [running]:
druid-exporter/utils.GetHealth(0xc0000fa240, 0x32, 0x0)
        ~/repo/druid-exporter/utils/http.go:22 +0x270
druid-exporter/collector.GetDruidHealthMetrics(0x0)
        ~/repo/druid-exporter/collector/druid.go:24 +0x179
druid-exporter/collector.(*MetricCollector).Collect(0xc0000bacc0, 0xc000446120)
        ~/repo/druid-exporter/collector/druid.go:100 +0x37
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        ~/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        ~/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:454 +0x599
```

**Comment by Chester-Ong** [comment]
I can confirm that #16 fixes the above issue. Furthermore, it allows starting druid-exporter with a dead druid server which currently fails with the following error message.
```
{"err":"Get \"http://druid.opstreelabs.in/druid/indexer/v1/tasks\": dial tcp: lookup druid.opstreelabs.in: no such host","level":"error","msg":"Error while making http request","ts":"2020-05-26T01:47:46.633Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x73233d]

goroutine 1 [running]:
druid-exporter/utils.GetResponse(0xc0000fa3c0, 0x32, 0x8ff7c3, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0)
        ~/repo/druid-exporter/utils/http.go:43 +0x11d
druid-exporter/collector.GetDruidData(0x8ff7c3, 0x17, 0x0, 0x0, 0x475fea94982232a)
        ~/repo/druid-exporter/collector/druid.go:45 +0xa5
druid-exporter/collector.CollectTaskMetrics(0xc0000b2150)
        ~/repo/druid-exporter/collector/druid.go:120 +0x48
main.init.0()
        ~/repo/druid-exporter/main.go:38 +0x17f
```

**Comment by iamabhishek-dubey** [comment]
you have to use your own druid service URL. Below domain doesn't exist
```
http://druid.opstreelabs.in
```

Please see [this](https://github.com/opstree/druid-exporter#available-options-or-flags)

**Comment by iamabhishek-dubey** [comment]
Please reopen the issue if needed

**Comment by iamabhishek-dubey** [comment]
I have merged the PR as well
