### ISSUE TITLE
Error with druid 0.19.0

### ISSUE THREAD

**Issue by ibotheperfect** [opstree/druid-exporter#60]
Hi.
I just installed druid-exporter via docker image and getting below error. 

> 2020/10/06 12:15:47 http: panic serving X.X.X.X:48434: interface conversion: interface {} is nil, not string
 goroutine 21184 [running]:
net/http.(*conn).serve.func1(0xc0000b60a0)
/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x8b91a0, 0xc000c083c0)
/usr/local/go/src/runtime/panic.go:975 +0x3e3
druid-exporter/listener.DruidHTTPEndpoint.func1(0x9f4600, 0xc0000d00e0, 0xc0006a6200)
/go/src/druid-exporter/listener/druid_endpoint.go:33 +0x1596
net/http.HandlerFunc.ServeHTTP(0xc00008e4e0, 0x9f4600, 0xc0000d00e0, 0xc0006a6200)
/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000b0000, 0x9f4600, 0xc0000d00e0, 0xc0006a6000)
/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc0000d0000, 0x9f4600, 0xc0000d00e0, 0xc0006a6000)
/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0000b60a0, 0x9f5cc0, 0xc0002e82c0)
/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2962 +0x35c

Druid version is 0.19.0 and config on druid side like this 

>  druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.client.cache.CacheMonitor"] 
druid.emitter.logging.logLevel=info
druid.emitter=http
druid.emitter.http.recipientBaseUrl=http://exporter:8080/druid

Don't know what did I do wrong. Any idea?

**Comment by ibotheperfect** [comment]
In addition, request that cause error coming from coordinator and I saw this error message in logs.

> java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to X.X.X.X:8080 after 10 ms
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_252]
        at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:202) ~[async-http-client-2.5.3.jar:?]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.send(HttpPostEmitter.java:759) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.access$1900(HttpPostEmitter.java:464) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread$1.perform(HttpPostEmitter.java:672) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread$1.perform(HttpPostEmitter.java:668) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:87) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:115) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:105) ~[druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.sendWithRetries(HttpPostEmitter.java:666) [druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.emit(HttpPostEmitter.java:574) [druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.emitBatches(HttpPostEmitter.java:550) [druid-core-0.19.0.jar:0.19.0]
        at org.apache.druid.java.util.emitter.core.HttpPostEmitter$EmittingThread.run(HttpPostEmitter.java:503) [druid-core-0.19.0.jar:0.19.0]
Caused by: java.util.concurrent.TimeoutException: Request timeout to X.X.X.X:8080 after 10 ms
        at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43) ~[async-http-client-2.5.3.jar:?]
        at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50) ~[async-http-client-2.5.3.jar:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]

**Comment by ibotheperfect** [comment]
I realized problem is related with #54. I upgraded exporter from v0.8 to v0.9 and problem seems solved.
