### ISSUE TITLE
Panic while collecting emitted metrics

### ISSUE THREAD

**Issue by cloventt** [opstree/druid-exporter#92]
In production, we frequently see errors similar to this:
```
2021/02/04 16:13:23 http: panic serving *.*.*.*:29223: interface conversion: interface {} is nil, not string
goroutine 881818 [running]:
net/http.(*conn).serve.func1(0xc000c82280)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x8b91a0, 0xc000494060)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
druid-exporter/listener.DruidHTTPEndpoint.func1(0x9f4600, 0xc0007f61c0, 0xc00021c600)
        /go/src/druid-exporter/listener/druid_endpoint.go:33 +0x1596
net/http.HandlerFunc.ServeHTTP(0xc0001372c0, 0x9f4600, 0xc0007f61c0, 0xc00021c600)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001a6000, 0x9f4600, 0xc0007f61c0, 0xc00021c400)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001b4000, 0x9f4600, 0xc0007f61c0, 0xc00021c400)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000c82280, 0x9f5cc0, 0xc0010f0740)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c
time="2021-02-04T16:13:23Z" level=info msg="Successfully collected data from druid emitter, broker"
```
These errors seem to correspond with blank stretches in our Grafana dashboard that pull this data from Prometheus.

We are using Druid 0.19.0, and using the Docker image `quay.io/opstree/druid-exporter:v0.8` deployed to Kubernetes with the Helm chart. We have a Kubernetes Ingress forwarding the metrics into Kubernetes.

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/opstree/druid-exporter/pull/90
